### ISSUE TITLE
Dropping Babel from build

### ISSUE THREAD

**Issue by jtmthf** [reactql/kit.ts#5]
Right now the output of the TypeScript compiler is chained through Babel to keep parity with the original kit. As of now, it's not needed to use Babel. TypeScript alone is enough for both the dev and prod builds. Compiling with TypeScript results in a smaller build size due to having more efficient helpers and not needing the `regenerator-runtime`. This took 11 KB off of the vendor bundle.

Downside to removing Babel is primarily losing the `env` preset in which TypeScript has no current equivalent. Also losing access to Babel plugins is a downside as well. However, it should be easy enough for developers to reincorporate Babel if they feel it is needed.

**Comment by leebenson** [comment]
As long as we get the same level of browser support from TS' own polyfills (i.e. 'last 3 versions'), then dropping Babel sounds like a smart move. No need to double-transpile what TS is already doing.

It'll probably mean we lose version sync, but then that was probably always going to be the case -- I'm sure there will be TS related bumps that won't apply in the plain kit. I'm not concerned with that since we don't really use those versions anywhere other than in the changelog.

IMO, a good move.

**Comment by leebenson** [comment]
btw @jtmthf, `kit.ts` isn't implemented in the CLI yet. Is there any reason to wait until you've removed babel (i.e. will it change any of the build steps?), or shall I go ahead and add now?

**Comment by jtmthf** [comment]
@leebenson no the build step stays the same. It just drops the Babel loader and relies on TypeScript to translate to es5. Before I had TypeScript essentially just stripping type information and then relying on Babel to do all the transpilation.

**Comment by jtmthf** [comment]
Babel now fully dropped from build step.
